base:
  project: aissm_mlops
  random_state: 20
  target_col: charges

data_source:
  raw_dataset_csv: data/raw/insurance.csv

load_data:
  clean_data: data/processed/insurance_aiss.csv

split_data:
  train_path: data/processed/train_aissm.csv
  test_path: data/processed/test_aissm.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.6

model_path: models/models.joblib

reports:
  params: reports/params.json
  score: reports/scores.json